{
 "title": "test",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_project=\"test-gomaxprocs\"}[1m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "CPU Thottled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{container_label_com_docker_compose_project=\"test-gomaxprocs\"}[1m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Request count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job, method, uri) (rate(http_server_requests_seconds_count{uri != \"/prometheus\"}[1m]))",
     "legendFormat": "{{job}} - {{method}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Request Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (job, method, uri) (rate(http_server_requests_seconds_sum{uri != \"/prometheus\"}[1m])/rate(http_server_requests_seconds_count{uri != \"/prometheus\"}[1m]))",
     "legendFormat": "{{job}} - {{method}} - {{uri}}"
    }
   ]
  },
  {
   "title": "CPU Thottled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{container_label_com_docker_compose_project=\"test-gomaxprocs\"}[1m])/rate(container_cpu_cfs_periods_total{container_label_com_docker_compose_project=\"test-gomaxprocs\"}[1m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  }
 ]
}